update 2024-05-06 18:58:01 add arm64

diff --git a/.github/workflows/mirror.yaml b/.github/workflows/mirror.yaml
--- a/.github/workflows/mirror.yaml
+++ b/.github/workflows/mirror.yaml
@@ -10,6 +10,7 @@ on:
 env:
   PROJECT_NAME_REPO: "${GITHUB_REPOSITORY##*/}"
   DOCKER_IMAGES_FROM: "ollama/ollama:latest"
+  BUILD_VERSION: "latest"
   DOCKER_IMAGES_TAG: "latest"
 
 jobs:
@@ -28,7 +29,16 @@ jobs:
            imagetag=${{ env.DOCKER_IMAGES_FROM }}
            imagetag="${imagetag##*:}"
            echo "DOCKER_IMAGES_TAG=${imagetag}" >> "$GITHUB_ENV"
+           echo "FROM ${{ env.DOCKER_IMAGES_FROM }}" > Dockerfile
         shell: bash
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+        if: ( !cancelled() )
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        if: ( !cancelled() )
 
       - name: Log in to Docker Hub
         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
@@ -60,26 +70,62 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME_TENCENT }}
           password: ${{ secrets.DOCKER_PASSWORD_TENCENT }}
 
-      - name: PULL and push Docker images
+      - name: Extract metadata (tags, labels) for Docker
+        id: meta
         if: ( !cancelled() )
-        run: |
-           docker pull ${{ env.DOCKER_IMAGES_FROM }}
-           docker tag ${{ env.DOCKER_IMAGES_FROM }} ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
-           docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
-           docker tag ${{ env.DOCKER_IMAGES_FROM }} ccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
-           docker push ccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
-           docker tag ${{ env.DOCKER_IMAGES_FROM }} uswccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
-           docker push uswccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
-        shell: bash
-      - name: Dayly Artifact Cleanup
-        uses: jimschubert/delete-artifacts-action@v1
+        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
         with:
-          log_level: 'error'
-          min_bytes: '0'
-      - name: Delete workflow runs
-        uses: Mattraks/delete-workflow-runs@v2
+          images: |
+            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO  }}
+            ccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO  }}
+            uswccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO  }}
+          tags: |
+            ${{ env.BUILD_VERSION }}
+            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
+            type=raw,value=action-{{branch}}-{{date 'YYYYMMDD-HHmmss' tz='Asia/Shanghai'}}
+          flavor: |
+            latest=true
+          labels: |
+            maintainer=DockerFlys
+            org.opencontainers.image.title=${{ env.PROJECT_NAME_REPO  }}
+            org.opencontainers.image.description="${{ env.PROJECT_NAME_REPO  }} images update default mirrors"
+            org.opencontainers.image.vendor=DockerFlys
+            org.opencontainers.image.version=${{ env.BUILD_VERSION }}
+            org.opencontainers.image.licenses=MIT
+            org.opencontainers.image.source=https://github.com/${{ github.repository }}
+            org.opencontainers.image.revision=${{ github.sha }}
+            org.opencontainers.image.created=${{ github.event.created_at }}
+            org.opencontainers.image.url=https://github.com/${{ github.repository }}
+      - name: Build and push Docker images
+        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
+        if: ( !cancelled() )
         with:
-          retain_days: 0
-          keep_minimum_runs: 6
-      - name: Clean Up
-        uses: AutoModality/action-clean@v1
+          context: .
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          platforms: linux/amd64,linux/arm64
+          labels: ${{ steps.meta.outputs.labels }}
+      # - name: PULL and push Docker images
+      #   if: ( !cancelled() )
+      #   run: |
+      #      docker pull ${{ env.DOCKER_IMAGES_FROM }}
+      #      docker tag ${{ env.DOCKER_IMAGES_FROM }} ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
+      #      docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
+      #      docker tag ${{ env.DOCKER_IMAGES_FROM }} ccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
+      #      docker push ccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
+      #      docker tag ${{ env.DOCKER_IMAGES_FROM }} uswccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
+      #      docker push uswccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{ env.DOCKER_IMAGES_TAG }} ||true
+      #   shell: bash
+
+      # - name: Dayly Artifact Cleanup
+      #   uses: jimschubert/delete-artifacts-action@v1
+      #   with:
+      #     log_level: 'error'
+      #     min_bytes: '0'
+      # - name: Delete workflow runs
+      #   uses: Mattraks/delete-workflow-runs@v2
+      #   with:
+      #     retain_days: 0
+      #     keep_minimum_runs: 6
+      # - name: Clean Up
+      #   uses: AutoModality/action-clean@v1
